image: themattrix/tox

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - sudo apt-get update && apt-get install -y --no-install-recommends git
          - tox
